version: '3.8'
services:
  api:
    container_name: api-container
    restart: always
    build: ./
    ports: 
      - "9876:5000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo-backend
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"